- name: test
  deploys:
    version: "latest"
  config:
    AZURE_LOCATION: "northeurope"
    RESOURCE_NAME_PREFIX: "latest"
    ENVIRONMENT_NAME_PREFIX: "test"
# - name: staging
#   deploys:
#     version: "v0.0.1-latest"
#   config:
#     AZURE_LOCATION: "westeurope"
#     AZURE_NAME_PREFIX: "staging"
#     WEBAPI_NODE_ENV: "production"
# - name: prod
#   deploys:
#     version: "v0.0.1-65fb1c42b138e61e9f578b3a0091dbd5ac846c4a"
#   config:
#     AZURE_LOCATION: "eastus"
#     AZURE_NAME_PREFIX: "prod"
#     WEBAPI_NODE_ENV: "production"